### ISSUE TITLE
awx module: python executable not found

### ISSUE THREAD

**Issue by ondrejkopka** [mitogen-hq/mitogen#1085]
Hi, i'm running ansible with mitogen v. 0.3.7, playbook command:
```
ansible-playbook play.yml --limit 'target' --diff --tags awx_jobs
```

which includes this task:
```
- name: add projects xxxx xx & update for new playbooks
  awx.awx.project:
    controller_host: "{{ awx_hostname }}"
    controller_oauthtoken: "{{ awx_token }}"
    organization: "xxx"
    name: "{{ awx_project['name'] }}"
    description: "{{ awx_project['description'] | default(awx_project['name']) }}"
    scm_type: "git"
    scm_url: "git"
    scm_update_on_launch: true
    scm_branch: "{{ awx_project['scm_source'] }}"
    scm_clean: true
    credential: "credential"
    state: present
    default_environment: "{{ awx_ee_default }}"
    notification_templates_error:
      - "Slack"
    update_project: yes
    timeout: 300
  loop: "{{ awx_projects }}"
  loop_control:
    loop_var: awx_project
```

with `linear` stragety it's working as it should be but once i use `mitogen_linear` strategy, it will fail with this error:
```
failed: [target] (item={'name': 'xxxx', 'scm_source': 'xxx'}) => changed=false
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  ansible_loop_var: awx_project
  awx_project:
    name: xxxx
    scm_source: xxxx
  module_stderr: ''
  module_stdout: |-
    /bin/sh: 1: /usr/bin/python: not found
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 127
```

So far it fails only at this place, other tasks and playbooks are running smoothly since switching to mitogen.

* Which version of Ansible are you running?
ansible [core 2.15.8]
  config file = $HOMEansible/ansible.cfg
  configured module search path = ['$HOME/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible_venv/lib/python3.9/site-packages/ansible
  ansible collection location = /$HOME/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/opt/ansible_venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True

ansible binary is symlink: `/usr/local/bin/ansible -> /opt/ansible_venv/bin/ansible`
* Is your version of Ansible patched in any way?
no
* Are you running with any custom modules, or `module_utils` loaded?
no

* Have you tried the latest master version from Git?
no

* Do you have some idea of what the underlying problem may be?
no

* Mention your host and target OS and versions
Host Debian 11.7, target Debian 12.4
* Mention your host and target Python versions
Host Python 3.9.2, target 3.11.2
* If reporting a crash or hang in Ansible, please rerun with -vvv and include
[ansible_verbose_mode.log](https://github.com/user-attachments/files/15837371/ansible_verbose_mode.log)

* If reporting any kind of problem with Ansible, please include the Ansible
  version along with output of "ansible-config dump --only-changed".
[ansible_config_dump.txt](https://github.com/user-attachments/files/15837370/ansible_config_dump.txt)

Let me know in case you need any more details, thank you!
