### ISSUE TITLE
feat(ansible): Handle templated `ssh_user`

### ISSUE THREAD

**Issue by setpill** [mitogen-hq/mitogen#1116]
ansible-mitogen does not handle templated values in `ssh_user` .

Original context from !956 :

> [..] this does fix the `ssh_common_args`, but I am running also into the issue that a templated `ssh_user` is not correctly handled.

_Originally posted by @setpill in https://github.com/mitogen-hq/mitogen/issues/956#issuecomment-2225208105_

**Comment by setpill** [comment]
Usecase: in our environment we have ansible roles that have tasks that need to be executed by different users. For legacy and security reasons we cannot assume these users to have fixed names, so we need to provide them in variable form.

Let's say for example that a role executes some tasks as `build_user` and some tasks as `deploy_user`. We would then have a task (block) in the form of:

```yml
- name: Build something
  vars:
    ansible_user: "{{ build_user }}"
    ansible_password: "{{ build_pass }}"
    ansible_sudo_pass: "{{ build_pass }}"
  block:
    - [..]
 ```

Ansible-mitogen is not currently a drop-in replacement for this scenario, as it will not template these variables and pass the literal string `{{ build_user }}` as the SSH user, which fails.
