### ISSUE TITLE
`set_fact` values in `remote_user` lead to `AnsibleUndefinedVariable`

### ISSUE THREAD

**Issue by moreati** [mitogen-hq/mitogen#1166]
It seems that another bug came up after this fix. Now, variables defined in `set_fact` and used as `remote_user` seem not to reach the right context, and then the `do_template `method of the class `Templar` (`ansible/template/__init__.py`) raises `AnsibleUndefinedVariable`. As a result the task fails because of an undefined variable, which is actually defined. However variables defined before tasks:

```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    my_user: "my_user"

  tasks:
```
or as extra vars:

```bash
ansible-playbook -vv  test_playbooks/test_mitogen.yml -e "my_user=my_user"
```
seem to hit the right context and everything works fine.

Here is the task list used for the test:

```yaml
---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: "define user and host"
      set_fact:
        my_user: "my_user"
        my_host: "10.192.65.127"
        exec_command: "uname -a"

    - debug:
        var: my_user

    - name: "test"
      shell: "{{ exec_command }}"
      delegate_to: "{{ my_host }}"
      remote_user: "{{ my_user }}"
```

execution result:
```
PLAY [localhost] *****************************************************************************************************************************************************************************************
Wednesday 16 October 2024  17:51:01 +0000 (0:00:01.307)       0:00:01.307 *****

TASK [define user and host] ******************************************************************************************************************************************************************************
task path: /home/test/test_playbooks/test_mitogen.yml:7
ok: [localhost] => {"ansible_facts": {"exec_command": "uname -a", "my_host": "10.192.65.127", "my_user": "my_user"}, "changed": false}
Wednesday 16 October 2024  17:51:01 +0000 (0:00:00.064)       0:00:01.371 *****

TASK [debug] *********************************************************************************************************************************************************************************************
task path: /home/test/test_playbooks/test_mitogen.yml:13
ok: [localhost] => {
    "my_user": "my_user"
}
Wednesday 16 October 2024  17:51:01 +0000 (0:00:00.065)       0:00:01.437 *****

TASK [test] **********************************************************************************************************************************************************************************************
task path: /home/test/test_playbooks/test_mitogen.yml:16
fatal: [localhost -> 10.192.65.127]: FAILED! => {"msg": "'my_user' is undefined. 'my_user' is undefined"}

PLAY RECAP ***********************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

* Which version of Ansible are you running?
2.15.6
* Is your version of Ansible patched in any way?
No
* Have you tried the latest master version from Git?
Yes, I've tried  0.3.13 and  0.3.14
* Mention your host and target OS and versions
Host: Ubuntu 22.04.3 LTS
* Mention your host and target Python versions
Host: 3.10.12

_Originally posted by @maronovych-godaddy in https://github.com/mitogen-hq/mitogen/issues/1040#issuecomment-2417541867_

**Comment by moreati** [comment]
I think defining `ansible_user` in the inventory masks this. Which seems odd, probably because [variables override keywords](https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html#precedence-categories)

```
➜  mitogen git:(master) ✗ ANSIBLE_STRATEGY=mitogen_linear ansible-playbook -i ~/ansible_inventory.yml issue1166.yml 

PLAY [localhost] *****************************************************************************************************
...
TASK [command] *******************************************************************************************************
changed: [localhost -> u2404.mynet]
...
```

**Comment by moreati** [comment]
@maronovych-godaddy are you sure your playbook (in the description of this issue) only fails when using Mitogen?

I'm finding the following playbook fails with vanilla Ansible as well

```yaml
- hosts: localhost
  gather_facts: false
  strategy: linear
  tasks:
    - set_fact:
        my_user: root
        my_host: u2404.mynet
        exec_command: uname -a

    - debug:
        var: my_user

    - command: "{{ exec_command }}"
      delegate_to: "{{ my_host }}"
      remote_user: "{{ my_user }}"
```

I've tested with Ansible 2.10 through to 10 (with the aid of Tox). E.g.

```
$ tox
py311-mode_ansible-ansible2.10: commands[0]> ansible-playbook -i localhost,u2204.mynet /Users/alex/src/mitogen/issue1166.yml

PLAY [localhost] ***************************************************************************************************************************************************************************************************************************

TASK [set_fact] ****************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [localhost] => 
  my_user: root

TASK [command] *****************************************************************************************************************************************************************************************************************************
fatal: [localhost -> u2404.mynet]: FAILED! => 
  msg: '''my_user'' is undefined'

NO MORE HOSTS LEFT *************************************************************************************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

py311-mode_ansible-ansible2.10: exit 2 (0.23 seconds) /Users/alex/src/ansibles> ansible-playbook -i localhost,u2204.mynet /Users/alex/src/mitogen/issue1166.yml pid=8092
py311-mode_ansible-ansible2.10: FAIL ✖ in 0.23 seconds
...
  py311-mode_ansible-ansible2.10: FAIL code 2 (0.23=setup[0.00]+cmd[0.23] seconds)
  py311-mode_ansible-ansible3: FAIL code 2 (0.23=setup[0.00]+cmd[0.23] seconds)
  py311-mode_ansible-ansible4: FAIL code 2 (0.27=setup[0.00]+cmd[0.26] seconds)
  py311-mode_ansible-ansible5: FAIL code 2 (0.26=setup[0.00]+cmd[0.25] seconds)
  py311-mode_ansible-ansible6: FAIL code 2 (0.25=setup[0.00]+cmd[0.25] seconds)
  py311-mode_ansible-ansible7: FAIL code 2 (0.26=setup[0.00]+cmd[0.26] seconds)
  py311-mode_ansible-ansible8: FAIL code 2 (0.27=setup[0.00]+cmd[0.26] seconds)
  py311-mode_ansible-ansible9: FAIL code 2 (0.26=setup[0.00]+cmd[0.26] seconds)
  py311-mode_ansible-ansible10: FAIL code 2 (0.25=setup[0.00]+cmd[0.25] seconds)
  evaluation failed :( (2.33 seconds)
```

**Comment by maronovych-godaddy** [comment]
Yes, you’re right, that’s indeed how Ansible works. The variable passed to `remote_user` should be in the context of the host where we are attempting to run the task. For example, if we try to delegate this task to `localhost`, the variable `my_user` won’t be undefined because it’s defined in the context of localhost. However, if we want to run this command remotely, we need to pass this variable directly from the `hostvars` of the host in whose context this variable was defined, in the example above, that’s localhost
```yaml
    - command: "{{ exec_command }}"
      delegate_to: "{{ my_host }}"
      remote_user: "{{ hostvars['localhost']['my_user'] }}"
 ```
Prior to the release of Mitogen 0.3.12, it was possible to use variables defined in the localhost context directly, so I initially thought this was a feature of Mitogen. I investigated the changes in 0.3.12 and found that the issue with the undefined variable disappears in 0.3.12 and  0.3.13 after removing the import of `DOCUMENTATION` from `ansible.plugins.connection.ssh` in `mitogen_ssh.py`:
```python
 from ansible.plugins.connection.ssh import (
     DOCUMENTATION as _ansible_ssh_DOCUMENTATION,
 )
```
however then once again comes up ([initial issue](https://github.com/mitogen-hq/mitogen/issues/1040#issuecomment-2417541867))

I've assumed that this import might unexpectedly trigger some constructor that disrupts Mitogen’s flow, I'm not sure, but is this behavior expected?
