### ISSUE TITLE
Parameter "timeout" of module "ansible.builtin.wait_for_connection" is ignored

### ISSUE THREAD

**Issue by setpill** [mitogen-hq/mitogen#1249]
We have a task at the start of every deployment that tests for the presence of legacy credentials. It is of the form:

```
- name: Determine hosts with "{{ legacy_user }}" credentials
  ansible.builtin.wait_for_connection:
    timeout: 1
  register: legacy_reachable
  ignore_errors: yes
  vars:
    ansible_user: "{{ legacy_user }}"
    ansible_password: "{{ legacy_pass }}"
```

Without mitogen, this task returns in 1 second. With mitogen, it takes over 1 minute.

I had hoped a #1200 might fix this, however even with mitogen 0.3.22 it is still slow.

**Comment by setpill** [comment]
I tried rewriting the above in an attempt to streamline things;

```yaml
- name: Determine hosts with "{{ legacy_user }}" credentials
  ansible.builtin.ping:
    timeout: 1
  register: legacy_reachable
  ignore_unreachable: true
  vars:
    ansible_user: "{{ legacy_user }}"
    ansible_password: "{{ legacy_pass }}"
```

Unfortunately, it made no difference, so it seems the problem is not specific to the module mentioned.
