### ISSUE TITLE
mitogen 0.3.x: async with docker_container hangs forever

### ISSUE THREAD

**Issue by shane-axiom** [mitogen-hq/mitogen#835]
Hi, I have a minimally reproducible bug report of `async` not working (hanging until cancelled) with `community.docker.docker_container` using mitogen 0.3.x (or master) and ansible 2.10.9. 

__requirements.txt__
```
ansible>=2.10,<2.11
mitogen==0.3.0rc1
```

__playbook.yml__
```
---

- name: mitogen async test
  hosts: all
  tasks:
  - name: Test mitogen async
    become: yes
    async: 320
    poll: 3

    community.docker.docker_container:
      name: "mitogen-async-test"
      image: "debian:bullseye-slim"
      command: "echo mitogen async test"
```

bootstrap conda env
```
conda create -n mitogen-async python=3.8
conda activate mitogen-async
pip install -r requirements.yml
git clone https://github.com/mitogen-hq/mitogen.git
```

verify it works without mitogen
```
ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 ansible-playbook -u remoteuser -kKi 'someserver,' playbook.yml
```

doesn't work with pip installed mitogen 0.3.0rc1
```
ANSIBLE_STRATEGY_PLUGINS=./mitogen/ansible_mitogen/plugins/strategy ANSIBLE_STRATEGY=mitogen_linear ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 ansible-playbook -vvv -u remoteuser -kKi 'someserver,' playbook.yml
```

doesn't work with master mitogen
```
ANSIBLE_STRATEGY_PLUGINS=$(find "$CONDA_PREFIX/lib/" -type d -name "python*.*")/site-packages/ansible_mitogen/plugins/strategy ANSIBLE_STRATEGY=mitogen_linear ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 ansible-playbook -vvv -u remoteuser -kKi 'someserver,' playbook.yml
```

* Which version of Ansible are you running?

2.10.9

* Is your version of Ansible patched in any way?

no

* Are you running with any custom modules, or `module_utils` loaded?

no

* Have you tried the latest master version from Git?

yes

* Do you have some idea of what the underlying problem may be?

no

* Mention your host and target OS and versions

Host: Debian bullseye/sid
Target: Debian buster

* Mention your host and target Python versions

Host: 3.8.5
Target: 3.7.3

* If reporting a crash or hang in Ansible, please rerun with -vvv and include
  200 lines of output around the point of the error, along with a full copy of
  any traceback or error text in the log. Beware "-vvv" may include secret
  data! Edit as necessary before posting.
  
  (adding as attachment)
  
* If reporting any kind of problem with Ansible, please include the Ansible
  version along with output of "ansible-config dump --only-changed".

`ansible-config dump --only-changed` has no output (no config changed)
