### ISSUE TITLE
mitogen_via when running from inside and outside network

### ISSUE THREAD

**Issue by jcrsilva** [mitogen-hq/mitogen#842]
Hello,

First of all thank you for your fabulous work with this project.

This is not a bug but a usage clarification.

I use Ansible to configure a bunch of routers and APs in a network. I have the use case of wanting ansible to run both from inside the network and from outside. The network has a router with NAT which serves as a bastion host from outside.

My quick and dirty way of accomplishing this before mitogen was the following in my hosts file:

```yaml
# ...
# (on bastion)

vars:
        ansible_port: "{{ '22' if lookup('env','OUTSIDE') != 'true' else '22222' }}"
      hosts:
        inside:
          ansible_host: "{{ 'inside' if lookup('env','OUTSIDE') != 'true' else 'outside.example.com' }}"
# ...
# (on hosts)
      vars:
        ansible_ssh_common_args: '{{ '''' if lookup(''env'',''OUTSIDE'') != ''true'' else ''-o ProxyCommand="ssh -W %h:%p -p 22222 -i /etc/ansible/secrets/ansible -q ansible@outside.example.com"'' }}'

```

This would ensure that when an env var `OUTSIDE` exists and is set to `true`:
- The port for the bastion host changes to its external ssh port
- The hostname for the bastion changes to its external dns record
- When connecting to the hosts the ssh session is proxied via the bastion

When I switched to mitogen (and my play got way faster) this method stopped working, I assume because the proxycommand is either ignored or conflicts with the way mitogen connects to hosts.

I attempted to use `mitogen_via` in a similar fashion:

```yaml
mitogen_via: "{{ '' if lookup('env','OUTSIDE') != 'true' else 'inside' }}"
```

However I get the following error:

```
The error was: jinja2.exceptions.UndefinedError: "hostvars['{{ '' if lookup('env','OUTSIDE') != 'true' else 'inside' }}']" is undefined
```

I assume this is caused by the way in which mitogen is grabbing the host vars from the file. How should I go about getting this to work?

Thank you
