### ISSUE TITLE
Can't serve ansible.module_utils.distro._distro using default python3 packages on Rocky Linux.

### ISSUE THREAD

**Issue by sjpb** [mitogen-hq/mitogen#912]
Just trying to get ansible-mitogen working on a Rocky Linux 8.5 system. I'm using:
- python 3.6.8 (which is what `dnf install python3` provides) as I believe that is the latest which has access to the selinux bindings on EL8)
- ansible --version reports `core 2.11.9` (again, the current default pip-installed version for this python).
- I have tried both mitogen 0.3.2 (which is what pip installs) and the master branch.

I have a playbook like this:
```yaml
- hosts: all
  strategy: linear
  gather_facts: no
  become: yes
  tasks:
  - name: Install Python if necessary.
    raw: test -e /usr/bin/python3 || yum install -y python3

- hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - shell: hostname
```

it fails on the 2nd play with `The Mitogen master process was unable to serve 'ansible.module_utils.distro._distro'`.

I have searched the issues tracker, but anything relevant looks like it got fixed in 0.3.

Is this an acceptable python / ansible combination? I am a bit confused from the docs to be honest!

Thanks for any help, really interested to try this.
