### ISSUE TITLE
FreeBSD 12 with become_method 'doas' fails

### ISSUE THREAD

**Issue by gertvdijk** [mitogen-hq/mitogen#935]
### Summary

Getting permission errors when running with Mitogen strategy enabled for tasks with `become: yes`, only on FreeBSD target hosts in my inventory.

Setting `strategy: linear` on the play (disabling Mitogen) resolves the issue.

It could be that the use of passwordless _doas_ may be related.

### Steps to reproduce

I'm not sure what exact parts are specific to the issue, but I think I've narrowed it down quit a bit to a few steps.

1. Have a FreeBSD 12.3 with `/usr/local/etc/doas.conf` configured to have a no-password configuration, e.g.:
   ```
   permit nopass :wheel as root
   ```
2. Try to run a play that includes a task that does `become: yes`, run it in regular/non-check mode, e.g.:

   ```yaml
   - hosts: myfreebsdhost
     tasks:
       - name: My task that needs become
         copy:
           # updates every run for easier demonstration of the bug
           content: "{{ ansible_date_time.iso8601 }}"
           dest: /root/repro-bug-test-ansible-become-mitogen
           mode: "0600"
           owner: root
           group: wheel
         become: yes
         # with 'permit nopass :wheel as root' in doas configuration we don't
         # need a password for the current ansible_user in the 'wheel' group.
         become_method: doas
   ```

Yields:
```
fatal: [myfreebsdhost]: FAILED! => {"changed": false, "checksum": "f456ead109c64fbdc5c49531c9430328d05acba2", "msg": "Destination /root not writable"}
```

Adding `strategy: linear` (disabled Mitogen) resolves it.
```diff
@@ -1,4 +1,5 @@
 - hosts: myfreebsdhost
+  strategy: linear
   tasks:
     - name: My task that needs become
       copy:
```

```
TASK [My task that needs become]
--- before: /root/repro-bug-test-ansible-become-mitogen
+++ after: /path/to/home/.ansible/tmp/ansible-local-10166chrp255n/tmppsv0ih_d
@@ -1 +1 @@
-2022-06-16T10:14:18Z
\ No newline at end of file
+2022-06-16T11:17:55Z
\ No newline at end of file

changed: [myfreebsdhost]
```

### Versions used

source host runs Debian 10 but with pyenv+direnv managed venv to upgrade it to mainline latest versions, see below.

target host FreeBSD 12.3-RELEASE-p3 with `ansible_python_interpreter=/usr/local/bin/python3.8` (just to pin that, avoid autodetect)

```console
$ pip --version
pip 22.1.2 from /path/to/my/ansible/repo/.direnv/python-3.10.5/lib/python3.10/site-packages/pip (python 3.10)
$ pip list
[...]
Package        Version
-------------- -------
ansible        5.9.0
ansible-core   2.12.6
cffi           1.15.0
click          8.1.3
cryptography   37.0.2
Jinja2         3.1.2
MarkupSafe     2.1.1
netaddr        0.8.0
packaging      21.3
passlib        1.7.4
pep517         0.12.0
pip            22.1.2
pip-tools      6.6.2
pycparser      2.21
pyparsing      3.0.9
PyYAML         6.0
resolvelib     0.5.4
setuptools     62.3.3
setuptools-scm 6.4.2
toml           0.10.2
tomli          2.0.1
wheel          0.37.1
```
mitogen 660d3e088501816edc12f4b98e9e92a35f68c707 (=v0.3.3)

Which is currently the same as `master` branch, so yes this also happens on master. 😅 

```console
$ git log --oneline v0.3.3..origin/master 
d71fb672 (origin/master, origin/HEAD, master) Begin v0.3.4.dev0
```

Plain fresh Ansible version pip-installed in the venv printed above, venv provisioned by direnv but I think that doesn't matter.

Double checked that this is still reproducible with all custom modules removed.

I've installed Ansible-Mitogen by a git clone on `./third_party/mitogen` (well, git-submodule) and setting the `ANSIBLE_STRATEGY`/`ANSIBLE_STRATEGY_PLUGINS` env vars via direnv.

```console
$ ansible-config dump --only-changed
DEFAULT_ACTION_PLUGIN_PATH(/path/to/my/ansible/ansible.cfg) = ['/path/to/my/ansible/plugins/actions']
DEFAULT_FORKS(/path/to/my/ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/path/to/my/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/path/to/my/ansible/ansible.cfg) = ['/path/to/my/ansible/testinventory']
DEFAULT_ROLES_PATH(/path/to/my/ansible/ansible.cfg) = ['/path/to/my/ansible/roles']
DEFAULT_STRATEGY(env: ANSIBLE_STRATEGY) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(env: ANSIBLE_STRATEGY_PLUGINS) = ['/path/to/my/ansible/third_party/mitogen/ansible_mitogen/plugins/strategy']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /path/to/my/ansible/scripts/get-ansible-vault-password
INTERPRETER_PYTHON(/path/to/my/ansible/ansible.cfg) = auto
RETRY_FILES_ENABLED(/path/to/my/ansible/ansible.cfg) = False
```

Hope this is sufficient, please LMK how/what to provide more as details. I'm just kind of clueless where to dig further. I did notice custom code for doas on FreeBSD in the mitogen repo - haven't yet looked into it.
