### ISSUE TITLE
delegate_to fails to discover the correct python interpreter for the targets

### ISSUE THREAD

**Issue by garthwilliamson** [mitogen-hq/mitogen#955]
Please drag-drop large logs as text file attachments.

Feel free to write an issue in your preferred format, however if in doubt, use
the following checklist as a guide for what to include.

* Which version of Ansible are you running? 2.12
* Is your version of Ansible patched in any way? no
* Are you running with any custom modules, or `module_utils` loaded? no

* Have you tried the latest master version from Git? no
* Do you have some idea of what the underlying problem may be?

delegate_to (with a loop?) doesn't use discover the right python interpreter

This isn't good when the target OS of delegate_to is trusty - it tries to use python 3.4 rather than 2.7

**Comment by garthwilliamson** [comment]
Minimal reproduction:

```yaml
- name: Deploy to nodes
  hosts: bionic-hosts
  serial: 1
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Do the thing
      ansible.builtin.command: ls
      loop:
        - trusty-host1
        - trusty-host2
        - trusty-host3
      delegate_to: "{{ item }}"

```

It succeeds for the first host, then fails for the rest.

**Comment by garthwilliamson** [comment]
The problem is probably at least partly that `self._connection.delegate_to_hostname` doesn't change for each iteration through the loop.

**Comment by GhostLyrics** [comment]
Interestingly - and perhaps related - mitogen also fails to correctly use `ansible_python_interpreter: auto` _when set in the inventory_ instead of `ansible.cfg`. 

In my scenario, I had set auto in the `all` group and a path in a subgroup `legacy` for older hosts.
I then wrote a playbook that deployed to a host in and delegated a task to a host in `legacy`.

Ansible with mitogen
- discovered the interpreter on the first host
- **reused the discovered interpreter** on the host in the subgroup instead of taking it from the variable.

If I uncomment `strategy = mitogen_linear` in `ansible.cfg` it works as intended.
If I leave the strategy as mitogen and then move the setting from the `all` group in inventory to `interpreter_python = auto` in `ansible.cfg` it also works as intended.

(this was with mitogen 0.3.31)

**Comment by moreati** [comment]
@GhostLyrics What version of Ansible are you using? Could you create a minimal reproducer? Perhaps based on Garth's

**Comment by manzsolutions-svsc** [comment]
Taking over for @GhostLyrics with the same wonderfully weird Ansible setup, our most minimal reproducer is 

```yaml
hosts: source
tasks:
    - name: Test something
      ansible.builtin.stat:
        path: /
      delegate_to: "{{ destination }}"
      loop: [ … a lot … ]
      loop_control:
        loop_var: destination
```

Our basic setup:

* `interpreter_python = auto` in `ansible.cfg`
* Ansible 2.16 (for rhel7 compatibility)
* A wild, *wild* mix of RHEL and Debian versions
* `ansible_python_interpreter` either not set, or only inconsistently, because it does not matter for most hosts

What we can, broadly, observe is that as soon as we enable mitogen, we get an error following the pattern

```
{"ansible_loop_var": "destination", "destination": "HOST TO BE DELEGATED TO", "msg": "EOF on stream; last 100 lines received:\nbash: /usr/bin/SOME_PYTHON_VERSION: No such file or directory", "unreachable": true}
```

Where SOME_PYTHON_VERSION is an automatically chosen python version (or compatibility symlink) that exists on the source host but not on the destination host.

Some combinations can solve or mask this issue easily:
* ✔️ If the source host has `ansible_python_interpreter` set, the destination host will correctly use autodiscovery
* ✔️ If the destination host has `ansible_python_interpreter` set, it will be used regardless of source settings
* ❓ If you delegate from a Debian host, the autodiscovered interpreter is `/usr/bin/python3`, which is broadly available (even if it's not necessarily the version you want)
  * Still explodes if you delegate to a host too old for python 3 (I know, I know...)
* ❓ If you delegate from a host still running ansible with python 2 (I know, I know…) Ansible seems to default to `/usr/bin/python` and many distributions ship symlinks from that to either python2 or python3 (again, no guarantee it's the python version you want)

So a lot of combinations will either work as intended, accidentally work, or accidentally *almost* work until you hit an edge case like `ansible.builtin.dnf` that explodes if it touches the wrong python version.

In addition to this mitogen specific issue, fact caching can also create *tons* of extra problems, but I think that should be out of scope for this discussion.
